layout: home
title: Just A Thought
description: A blog of reflection on faith, marriage, culture, technology, and camping.
baseurl: "/Just-a-Thought"
url: "https://jeffthomasiii.github.io"
theme: minima

# Minima 3.x navigation support:
minima:
  social_links:
    github: jeffthomasiii
  header_pages:
    - about.md
    - tags.md
    
# Optional: enable GitHub Pages plugins
# plugins:
#  - jekyll-feed
