title: Just A Thought
description: A blog of reflection on faith, marriage, culture, technology, and camping.
baseurl: "/Just-a-Thought"
url: "https://jeffthomasiii.github.io"
theme: minima
excerpt_separator: "<!--more-->"
permalink: /:categories/:title/ 

minima:
  social_links:
    github: jeffthomasiii
    twitter: jeffthomasiii
    linkedin: jeffthomasiii
    instagram: jeffthomasiii
    rss: true
  header_pages:
    - about.md
    - tags.md
  show_excerpts: true

# Add this to _config.yml
plugins:
  - jekyll-feed